name: Build

on:
  push:
  repository_dispatch:
    types: [run_build]
  schedule:
  - cron: "0 */12 * * *"

jobs:
  build-linux-arm:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake cmake-data git build-essential autoconf libtool texinfo bison flex pkg-config python
    - name: Clone
      run: |
        export REV=dirty-$(git describe --always)
        git clone https://github.com/SonicMastr/buildscripts.git
        chmod +x *.sh 
    - name: Build
      run: |
        cd buildscripts
        git config --global user.email "builds@travis-ci.com"
        git config --global user.name "Travis CI"
        mkdir build
        cd build
        cmake ..
        make -j$(nproc) tarball
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: vitasdk-linux-arm
        path: buildscripts/build/*.tar.bz2
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/heads/master')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: buildscripts/build/*.tar.bz2
        overwrite: true
        file_glob: true
        tag: master-linux-arm-v2.${{github.run_number}}     
        release_name: master-linux-arm-v2.${{github.run_number}}
